---
base_url: "http://localhost:8080"
checks:
  - name: help 
    path: "/help"
    method: GET
    response_code: 401
    auth:
      login: foo
      password: bar
  - name: status
    path: "/status"
    method: GET
    response_code: 200
    response_body: "on"
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: SuperToken
  - name: ping
    path: "/ping"
    method: GET
    response_code: 404
    response_body: '{"message":"pong"}'
    playload: '{"message":"pong"}'
  - name: foo
    path: "/foo"
    method: POST
    response_code: 200
    playload: '{"user":"admin","password":"secret"}'
    response_body: '{"status":"admin"}'